// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Footer: typeof import('./components/ld/Footer.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    IconBase: typeof import('./components/c/IconBase.vue')['default']
    Lightbox: typeof import('./components/c/Lightbox.vue')['default']
    Progress: typeof import('./components/c/Progress.vue')['default']
    Sidebar: typeof import('./components/ld/Sidebar.vue')['default']
    SidebarSearch: typeof import('./components/ld/SidebarSearch.vue')['default']
  }
}

export { }
